import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Next.js ENV variables PoC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={inter.className}>
          <h1 className={styles.title}>Next.js ENV variables PoC</h1>
          <div className={styles.grid}>
            <Link href="/file" className={styles.card}>
              Using .env file
            </Link>
            <Link href="/ssr" className={styles.card}>
              Using getServerSideProps
            </Link>
            <Link href="/internal-api" className={styles.card}>
              Using internal API
            </Link>
          </div>
        </div>
      </main>
    </>
  )
}
